#!/bin/bash

set -e

cd "$(dirname "$0")/.."

function debian_sid_sources()
{
  mv /etc/apt/sources.list "/etc/apt/sources.list.$(date -I).bak"
  cp -f ./etc/apt/sources.list /etc/apt/sources.list
}

function install_pkgs()
{
  debian_sid_sources

  apt-get update -y

  # shellcheck disable=SC2046
  apt-get install -y --no-install-recommends $(tr '\n' ' ' < ./apt.list)
}

./script/setup

if [[ -f "/usr/bin/fdfind" ]]; then
  ln -s /usr/bin/fdfind /usr/bin/fd
fi

install_pkgs
